#ifndef MQTT_TOPICS_HH
#define MQTT_TOPICS_HH

#include "ha_device_info.hh"

// ----- MQTT Topics -----
#define MQTT_TOPIC_BASE "hass/" HA_DEVICE_ID "/"
#define MQTT_TOPIC_AVAILABILITY MQTT_TOPIC_BASE "avail"
#define MQTT_TOPIC_STATE_GENERAL MQTT_TOPIC_BASE "state/gnrl"
#define MQTT_TOPIC_STATE_SPEED MQTT_TOPIC_BASE "state/speed"
#define MQTT_TOPIC_STATE_QUIET MQTT_TOPIC_BASE "state/quiet"
#define MQTT_TOPIC_STATE_POSITION_STEPS MQTT_TOPIC_BASE "state/steps"
#define MQTT_TOPIC_STATE_POSITION_MM MQTT_TOPIC_BASE "state/mm"
#define MQTT_TOPIC_STATE_POSITION_PERCENT MQTT_TOPIC_BASE "state/percent"
#define MQTT_TOPIC_COMMAND_GENERAL MQTT_TOPIC_BASE "cmd/gnrl"
#define MQTT_TOPIC_COMMAND_SPEED MQTT_TOPIC_BASE "cmd/speed"
#define MQTT_TOPIC_COMMAND_QUIET MQTT_TOPIC_BASE "cmd/quiet"
#define MQTT_TOPIC_COMMAND_POSITION_STEPS MQTT_TOPIC_BASE "cmd/steps"
#define MQTT_TOPIC_COMMAND_POSITION_MM MQTT_TOPIC_BASE "cmd/mm"
#define MQTT_TOPIC_COMMAND_POSITION_PERCENT MQTT_TOPIC_BASE "cmd/percent"
#define MQTT_TOPIC_SENSOR_MICRO_STEPS MQTT_TOPIC_BASE "snsr/micrstp"
#define MQTT_TOPIC_SENSOR_HALF_STEP_DELAY MQTT_TOPIC_BASE "snsr/stepdelay"

// ----- Device Discovery -----
#define HA_DEVICE_MQTT_DISCOVERY_TOPIC "hass/device/" HA_DEVICE_ID "/config"

#endif
